#!/bin/bash
clear
echo "---- Tool Install XFCE 4 Ngrok 1.1.0 ----"
echo "### Update 10/4/2021 ###"
echo ""
apt update
apt install sudo
sudo apt install update
sudo apt install wget
sudo apt install xrdp
sudo apt-get update
sudo apt install xfce4 xfce4-goodies tightvncserver
sudo apt-get clean
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
unzip ngrok-stable-linux-amd64.zip
clear
echo "---- Select You Password ----"
vncpasswd
clear
wget https://raw.githubusercontent.com/TranAnhOffical/codelab-project/main/start-desktop
clear
echo "---- Config ----"

echo "---- Add You Ngrok Auth Token To Start Ngrok ----"
echo "Type 'bash start-desktop' to starting Desktop"
